const INITIAL = "INITIAL",
      FETCHING = "FETCHING",
      RESOLVED = "RESOLVED",
      ERROR = "ERROR",
      MAKE_REQUEST = "MAKE_REQUEST",
      FETCH_SUCCESS = "FETCH_SUCCESS",
      FETCH_FAIL = "FETCH_FAIL",
      TOGGLE_MODAL = "TOGGLE_MODAL";

export const STATE = {
  URL: {
    INITIAL,
    FETCHING,
    RESOLVED,
    ERROR
  }
}

export const ACTION_TYPES = {
  MAKE_REQUEST,
  FETCHING,
  FETCH_SUCCESS,
  FETCH_FAIL,
  TOGGLE_MODAL
}